Bookify.Web/Controllers/BookCopiesController.cs
using AutoMapper;
using Bookify.Web.Core.Models;
using Bookify.Web.Core.ViewModels.BookCopies;
using Bookify.Web.Core.ViewModels.Category;
using Microsoft.AspNetCore.Mvc;

namespace Bookify.Web.Controllers
{
    public class BookCopiesController : Controller
    {
        private readonly BookCopyRepository repo;
        private readonly BooksRepository booksRepository;
        private readonly IMapper mapper;

        public BookCopiesController(BookCopyRepository repo , BooksRepository booksRepository  , IMapper mapper)
        {
            this.repo = repo;
            this.booksRepository = booksRepository;
            this.mapper = mapper;
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var copy = repo.GetById(id);
            if (copy == null)
                return NotFound();
            copy.LastUpdatedOn = DateTime.Now;
            copy.IsDeleted = true;
            repo.Save();
            return RedirectToAction("Details" , "Books" , new { id = copy.BookId });
        }
        public IActionResult Retrieve(int id)
        {
            var copy = repo.GetById(id);
            if (copy == null)
                return NotFound();
            copy.LastUpdatedOn = DateTime.Now;
            copy.IsDeleted = false;
            repo.Save();
            return RedirectToAction("Details", "Books" , new {id = copy.BookId});
        }
        public IActionResult Create(int bookId)
        {
            var book = booksRepository.GetById(bookId);
            if (book == null)
                return NotFound();
            var viewModel = new BookCopyFormViewModel 
            { 
                BookId = bookId,
                ShowRentalInput = book.IsAvailableForRental
            };
            return View("Form" , viewModel);
        }
        [HttpPost , ValidateAntiForgeryToken]
        public IActionResult Create(BookCopyFormViewModel vmodel)
        {
            if (!ModelState.IsValid) 
                return BadRequest();
            var book = booksRepository.GetById(vmodel.BookId);
            if (book == null)
                return NotFound();
            BookCopy copy = new BookCopy
            {
                EditionNumber = vmodel.EditionNumber,
                IsAvailableForRental = book.IsAvailableForRental && vmodel.IsAvailableForRental,
            };
            book.Copies.Add(copy);
            repo.Save();
            return RedirectToAction("Details", "Books", new { id = copy.BookId });
        }
        public IActionResult Update(int id)
        {
            var copy = repo.GetByIdWithBook(id);
            if (copy == null)
                return NotFound();
            var viewModel = mapper.Map<BookCopyFormViewModel>(copy);
            viewModel.ShowRentalInput = copy.Book!.IsAvailableForRental;
            return View("Form", viewModel);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Update(BookCopyFormViewModel vmodel)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var copy = repo.GetByIdWithBook(vmodel.Id);
            if (copy == null)
                return NotFound();
            copy.EditionNumber = vmodel.EditionNumber;
            copy.IsAvailableForRental = copy.Book!.IsAvailableForRental && vmodel.IsAvailableForRental;
            copy.LastUpdatedOn = DateTime.Now;
            repo.Save();
            return RedirectToAction("Details", "Books", new { id = copy.BookId });
        }
    }
}

Bookify.Web/Views/Shared/_Aside.cshtml
@using System.Security.Claims
@{
    // Get the current controller and action names from the route data
    var currentController = ViewContext.RouteData.Values["controller"]?.ToString();
    var currentAction = ViewContext.RouteData.Values["action"]?.ToString();
}

<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 fixed-start bg-white shadow-lg vh-100" id="sidenav-main" style="width: 250px;">
    <div class="sidenav-header text-center py-4">
        <div class="mx-3 py-3">
            <div class="d-flex align-items-center text-dark">
                <i class="bi bi-person-circle text-dark fs-2"></i>
                <div class="d-flex flex-column align-items-start ms-2">
                    <span class="text-dark fs-bold">@User.Identity?.Name</span>
                    <small class="text-muted">@User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value</small>
                </div>
            </div>
        </div>
    </div>
    <hr class="horizontal dark mt-0 mb-2">
    <div class="collapse navbar-collapse w-auto h-auto" id="sidenav-collapse-main">
        <ul class="navbar-nav">
            <li class="nav-item mt-2">
                @{
                    // Determine if this link should be active
                    var booksActiveClass = (currentController == "Books" && currentAction == "Index") ? "active bg-gradient-primary" : "";
                }
                <a class="nav-link text-dark @booksActiveClass" asp-area="" asp-controller="Books" asp-action="Index">
                    <i class="bi bi-book-fill text-dark fs-6"></i>
                    <span class="nav-link-text ms-1">Books</span>
                </a>
            </li>
            <li class="nav-item">
                @{
                    var categoriesActiveClass = (currentController == "Categories" && currentAction == "Index") ? "active bg-gradient-primary" : "";
                }
                <a class="nav-link text-dark @categoriesActiveClass" asp-area="" asp-controller="Categories" asp-action="Index">
                    <i class="bi bi-tags-fill text-dark fs-6"></i>
                    <span class="nav-link-text ms-1">Categories</span>
                </a>
            </li>
            @if (User.Identity != null && User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                <li class="nav-item">
                    @{
                        var authorsActiveClass = (currentController == "Authors" && currentAction == "Index") ? "active bg-gradient-primary" : "";
                    }
                    <a class="nav-link text-dark @authorsActiveClass" asp-area="" asp-controller="Authors" asp-action="Index">
                    <i class="bi bi-person-circle text-dark fs-6"></i>
                    <span class="nav-link-text ms-1">Authors</span>
                </a>
            </li>
            }
            <li class="nav-item">
                @{
                    var subscribersActiveClass = (currentController == "Subscribers" && currentAction == "Index") ? "active bg-gradient-primary" : "";
                }
                <a class="nav-link text-dark @subscribersActiveClass" asp-area="" asp-controller="Subscribers" asp-action="Index">
                    <i class="bi bi-people-fill text-dark fs-6"></i>
                    <span class="nav-link-text ms-1">Subscribers</span>
                </a>
            </li>

            @if (User.Identity != null && User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                <li class="nav-item">
                    @{
                        var usersActiveClass = (currentController == "Users" && currentAction == "Index") ? "active bg-gradient-primary" : "";
                    }
                    <a class="nav-link text-dark @usersActiveClass" asp-area="" asp-controller="Users" asp-action="Index">
                        <i class="bi bi-person-plus-fill text-primary fs-4"></i>
                        <span class="nav-link-text ms-1">Users</span>
                    </a>
                </li>
            }
           
        </ul>
    </div>
</aside>

Bookify.Web/Views/Shared/_BookCopyRow.cshtml
@model BookCopyViewModel


<tr>
    <td class="text-center">
        @Model.SerialNumber
    </td>
    <td class="text-center">
        @Model.EditionNumber
    </td>
    <td class="text-center">
        <span class="badge bg-@((Model.IsDeleted) ? "danger" : "success")">
            @((Model.IsDeleted) ? "Deleted" : "Available")
        </span>
    </td>
    <td class="text-center">
        <span class="badge bg-@((Model.IsAvailableForRental) ? "success" : "danger")">
            @((Model.IsAvailableForRental) ? " Available" : " Not Available")
        </span>
    </td>
    <td class="text-center">
        @Model.CreatedOn.ToString("MM/dd/yyyy HH:mm")
    </td>
    @if (User?.Identity?.IsAuthenticated == true)
    {
        <td class="text-center">
            <a asp-controller="BookCopies" asp-action="Update" asp-route-id="@Model.Id" class="btn btn-sm btn-outline-info mb-0">Edit</a>
            @if (!Model.IsDeleted)
            {
                <form asp-controller="BookCopies" asp-action="Delete" asp-route-id="@Model.Id" method="post" style="display:inline;">
                    <button type="submit" class="btn btn-sm btn-outline-danger mb-0">Delete</button>
                </form>
            }
            else
            {
                <form asp-controller="BookCopies" asp-action="Retrieve" asp-route-id="@Model.Id" method="post" style="display:inline;">
                    <button type="submit" class="btn btn-sm btn-outline-dark mb-0">Retrieve</button>
                </form>
            }
        </td>
    }
</tr>

Bookify.Web/Views/Shared/_DataTablesCardHeader.cshtml
<div class="card-header align-items-center py-5 gap-2 gap-md-5">
    <div class="card-title">
        <div class="d-flex align-items-center position-relative my-1">
            <span class="svg-icon svg-icon-1 position-absolute ms-4">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor"></rect>
                    <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor"></path>
                </svg>
            </span>
            <input type="text" data-kt-filter="search" class="form-control form-control-solid w-250px ps-14" placeholder="Search..." />
        </div>
        <div id="kt_datatable_example_1_export" class="d-none"></div>
    </div>
    <div class="card-toolbar flex-row-fluid justify-content-end gap-5">
        <button type="button" class="btn btn-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
            <span class="svg-icon svg-icon-2">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <rect opacity="0.3" width="12" height="2" rx="1" transform="matrix(0 -1 -1 0 12.75 19.75)" fill="currentColor"></rect>
                    <path d="M12.0573 17.8813L13.5203 16.1256C13.9121 15.6554 14.6232 15.6232 15.056 16.056C15.4457 16.4457 15.4641 17.0716 15.0979 17.4836L12.4974 20.4092C12.0996 20.8567 11.4004 20.8567 11.0026 20.4092L8.40206 17.4836C8.0359 17.0716 8.0543 16.4457 8.44401 16.056C8.87683 15.6232 9.58785 15.6554 9.9797 16.1256L11.4427 17.8813C11.6026 18.0732 11.8974 18.0732 12.0573 17.8813Z" fill="currentColor"></path>
                    <path opacity="0.3" d="M18.75 15.75H17.75C17.1977 15.75 16.75 15.3023 16.75 14.75C16.75 14.1977 17.1977 13.75 17.75 13.75C18.3023 13.75 18.75 13.3023 18.75 12.75V5.75C18.75 5.19771 18.3023 4.75 17.75 4.75L5.75 4.75C5.19772 4.75 4.75 5.19771 4.75 5.75V12.75C4.75 13.3023 5.19771 13.75 5.75 13.75C6.30229 13.75 6.75 14.1977 6.75 14.75C6.75 15.3023 6.30229 15.75 5.75 15.75H4.75C3.64543 15.75 2.75 14.8546 2.75 13.75V4.75C2.75 3.64543 3.64543 2.75 4.75 2.75L18.75 2.75C19.8546 2.75 20.75 3.64543 20.75 4.75V13.75C20.75 14.8546 19.8546 15.75 18.75 15.75Z" fill="currentColor"></path>
                </svg>
            </span>
            Export
        </button>
        <div id="kt_datatable_example_export_menu" class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-200px py-4" data-kt-menu="true">
            <div class="menu-item px-3">
                <a href="#" class="menu-link px-3" data-kt-export="copy">
                    Copy to clipboard
                </a>
            </div>
            <div class="menu-item px-3">
                <a href="#" class="menu-link px-3" data-kt-export="excel">
                    Export as Excel
                </a>
            </div>
            <div class="menu-item px-3">
                <a href="#" class="menu-link px-3" data-kt-export="csv">
                    Export as CSV
                </a>
            </div>
            <div class="menu-item px-3">
                <a href="#" class="menu-link px-3" data-kt-export="pdf">
                    Export as PDF
                </a>
            </div>
        </div>
        <div id="kt_datatable_example_buttons" class="d-none"></div>
    </div>
</div>

Bookify.Web/Views/Shared/_Header.cshtml
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 my-2 shadow-none border-radius-xl bg-dark" id="navbarBlur" data-scroll="false">
    <div class="container-fluid py-1 px-3">
        <a class="navbar-brand m-0" asp-controller="Home" asp-action="Index">
            <img src="~/assets/img/logo.png" class="navbar-brand-img" alt="main_logo" style="max-height: 2.5rem;">
        </a>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4 justify-content-end" id="navbar">
            <ul class="navbar-nav justify-content-end">
                <partial name="_LoginPartial" />
                <li class="nav-item dropdown px-3 d-flex align-items-center">
                    
                </li>
                <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                    <a href="javascript:;" class="nav-link text-white p-0" id="iconNavbarSidenav">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line bg-white"></i>
                            <i class="sidenav-toggler-line bg-white"></i>
                            <i class="sidenav-toggler-line bg-white"></i>
                        </div>
                    </a>
                </li>
                 @if (User.Identity != null && User.Identity.IsAuthenticated)
                 {
                    <li class="nav-item d-flex align-items-center">
                        <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <i class="bi bi-box-arrow-right fs-6"></i>
                            <span class="d-sm-inline d-none">Sign out</span>
                        </a>
                    </li>
                }
                else
                {
                    <li class="nav-item d-flex align-items-center">
                        <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/Login" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <i class="bi bi-box-arrow-right fs-6"></i>
                            <span class="d-sm-inline d-none">Log in</span>
                        </a>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>

Bookify.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookify.Web</title>
    <script type="importmap"></script>
    @* <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script> *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" />
    <!-- bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <!-- CSS Files -->
    <link rel="stylesheet" href="~/Bookify.Web.styles.css" asp-append-version="true" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/lib/select2-bootstrap-5-theme/select2-bootstrap-5-theme.min.css" rel="stylesheet" />
    <link href="~/lib/flatpickr/flatpickr.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/datatables.bootstrap4.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/datatables.bootstrap4.min.css" rel="stylesheet" />
    @await RenderSectionAsync("Styles", required: false)
    <link rel="stylesheet" href="~/assets/css/argon-dashboard.css?v=2.1.0" id="pagestyle" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>
<body class="g-sidenav-show bg-gray-100">
        <!-- Aside -->
    @if (User.Identity?.IsAuthenticated ?? false)
    {
        <partial name="_Aside" />
    }
        <!-- End Aside -->

    <main class="main-content position-relative border-radius-lg">
        <!-- Navbar -->
       <partial name="_Header"/>
        <!-- End Navbar -->

        <div class="container p-4">
            <div class="row">
                @RenderBody()
            </div>
        </div>

        <footer class="border-top footer">
            <div class="container-fluid pt-3">
                <div class="row align-items-center justify-content-lg-between">
                    <div class="col-lg-6 mb-lg-0">
                        <div class="copyright text-center text-sm text-muted text-lg-start">
                            &copy; 2025 - Bookify.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </main>
    <script src="~/assets/js/core/popper.min.js"></script>
    <script src="~/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="~/assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="~/assets/js/argon-dashboard.min.js?v=2.1.0"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/flatpickr/flatpickr.min.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="~/lib/bootbox.js/bootbox.all.js"></script>
    <script src="~/lib/bootbox.js/bootbox.all.min.js"></script>
    <script src="~/lib/datatables/js/jquery.datatables.min.js"></script>
    <script src="~/lib/datatables/js/jquery.datatables.js"></script>
    <script src="~/lib/datatables/js/datatables.bootstrap.js"></script>
    <script src="~/lib/datatables/js/datatables.bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Plugins", required: false)
</body>
</html>

Bookify.Web/Views/Shared/_ModalFooter.cshtml
<div class="modal-footer px-0">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">
        <span class="indicator-label">
            Save
        </span>
        <span class="indicator-progress">
            Please wait... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
        </span>
    </button>
</div>